import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { DynatraceClient } from "../http/client.js";
import type { Config } from "../types.js";
import { registerDqlTools } from "./dql.js";
import { registerDqlReferenceTools } from "./dql-reference.js";
import { registerDashboardReferenceTools } from "./dashboard-reference.js";
import { registerMetricsTools } from "./metrics.js";
import { registerEntitiesTools } from "./entities.js";
import { registerProblemsTools } from "./problems.js";
import { registerLogsTools } from "./logs.js";
import { registerTracesTools } from "./traces.js";
import { registerVulnerabilitiesTools } from "./vulnerabilities.js";
import { registerSettingsTools } from "./settings.js";
import { registerDashboardTools } from "./dashboards.js";
import { registerNotebookTools } from "./notebooks.js";
import { registerSloTools } from "./slos.js";
import { registerSyntheticTools } from "./synthetic.js";
import { registerConfigV1Tools } from "./config-v1.js";
import { registerOpenPipelineTools } from "./openpipeline.js";
import { registerDriftTools } from "./drift.js";
import { registerServerInfoTools } from "./server-info.js";
import { registerAutomationTools } from "./automation.js";
import { registerBucketTools } from "./buckets.js";
import { registerFilterSegmentTools } from "./filter-segments.js";
import { registerRecordDeletionTools } from "./record-deletion.js";
import { registerNotificationTools } from "./notifications.js";
import { registerEmailTools } from "./email.js";
import { registerExtensionsTools } from "./extensions.js";
import { registerIngestTools } from "./ingest.js";
import { registerAuditTools } from "./audit.js";
import { registerFeatureManagementTools } from "./feature-management.js";
import { registerIamTools } from "./iam.js";
import { registerExtractionTools } from "./extraction.js";
import { registerFieldsetTools } from "./fieldsets.js";
import { registerResourceStoreTools } from "./resource-store.js";
import { registerDavisAnalyzerTools } from "./davis-analyzers.js";
import { registerRawTools } from "./raw.js";
import { registerIamBoundaryTools } from "./iam-boundaries.js";
import { registerIamPolicyTools } from "./iam-policies.js";
import { registerIamReferenceTools } from "./iam-reference.js";
import { registerIamGroupTools } from "./iam-groups.js";
import { registerCostTools } from "./cost.js";
import { registerIamUserTools } from "./iam-users.js";
import { registerPermissionTools } from "./permissions.js";
import { registerPlatformTokenTools } from "./platform-tokens.js";

export interface ToolDeps {
  client: DynatraceClient;
  config: Config;
}

export function registerAllTools(server: McpServer, deps: ToolDeps): void {
  registerDqlTools(server, deps);
  registerDqlReferenceTools(server);
  registerDashboardReferenceTools(server);
  registerMetricsTools(server, deps);
  registerEntitiesTools(server, deps);
  registerProblemsTools(server, deps);
  registerLogsTools(server, deps);
  registerTracesTools(server, deps);
  registerVulnerabilitiesTools(server, deps);
  registerSettingsTools(server, deps);
  registerDashboardTools(server, deps);
  registerNotebookTools(server, deps);
  registerSloTools(server, deps);
  registerSyntheticTools(server, deps);
  registerConfigV1Tools(server, deps);
  registerOpenPipelineTools(server, deps);
  registerDriftTools(server, deps);
  registerServerInfoTools(server, deps);
  registerAutomationTools(server, deps);
  registerBucketTools(server, deps);
  registerFilterSegmentTools(server, deps);
  registerRecordDeletionTools(server, deps);
  registerNotificationTools(server, deps);
  registerEmailTools(server, deps);
  registerExtensionsTools(server, deps);
  registerIngestTools(server, deps);
  registerAuditTools(server, deps);
  registerFeatureManagementTools(server, deps);
  registerIamTools(server, deps);
  registerExtractionTools(server, deps);
  registerFieldsetTools(server, deps);
  registerResourceStoreTools(server, deps);
  registerDavisAnalyzerTools(server, deps);
  registerRawTools(server, deps);
  registerIamBoundaryTools(server, deps);
  registerIamPolicyTools(server, deps);
  registerIamReferenceTools(server);
  registerIamGroupTools(server, deps);
  registerCostTools(server, deps);
  registerIamUserTools(server, deps);
  registerPermissionTools(server, deps);
  registerPlatformTokenTools(server, deps);
}
